Repository pda5th-TheOne/front, pull requests merged in 2024-11, with the labels that each got.

#3 React 프로젝트 폴더 구조 및 필수 라이브러리 설정
  .gitignore
  package.json
  src/App.jsx
  src/main.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
  src/routers/AppRouter.jsx
Labels: 환경설정

#6 리액트 Docker 컨테이너화 및 CI/CD 파이프라인 구축
  .github/workflows/deploy.yml
  Dockerfile
  nginx.conf
Labels: 환경설정

#7 NGINX 설정 파일 오류 수정
  nginx.conf
Labels: 버그수정

#10 실습 페이지 UI 뼈대 구성 및 더미 데이터 추가
  src/App.jsx
  src/components/Logo.jsx
  src/components/UserName.jsx
  src/pages/Practice.jsx
  src/pages/practice/Answer.jsx
  src/pages/practice/Assignment.jsx
  src/pages/practice/Main.jsx
  src/pages/practice/Submit.jsx
  src/routers/AppRouter.jsx
Labels: 구현

#11 Origin/feat/#1 main page 1
  .prettierrc.cjs
  images/main_logo.png
  package.json
  src/App.css
  src/App.jsx
  src/components/Logo.jsx
  src/components/components.css
  src/pages/Home.jsx
  src/pages/MainPage.jsx
  src/pages/NotFound.jsx
  src/pages/main/Board.jsx
  src/pages/main/BoardList.jsx
  src/pages/main/Honey.jsx
  src/pages/main/Main.jsx
  src/pages/main/Question.jsx
  src/pages/main/main.css
  src/routers/AppRouter.jsx
Labels: 구현

#13 Dockerfile Node.js 버전 수정 핫픽스
  Dockerfile
  src/pages/Practice.jsx
  src/pages/practice/Main.jsx
  src/routers/AppRouter.jsx
Labels: 버그수정

#15 Feat/#14 login
  src/pages/Home.jsx
  src/pages/home/Login.jsx
Labels: 구현

#17 Nginx API 프록시 설정
  nginx.conf
  src/pages/home/Login.jsx
Labels: 구현

#19 Docker 네트워크 설정을 위한 GitHub Actions 및 Nginx 구성 수정
  .github/workflows/deploy.yml
  nginx.conf
Labels: 버그수정

#25 이미지 파일 경로 수정 및 public 폴더로 이동
  public/images/main_logo.png
  src/components/Logo.jsx
Labels: 버그수정

#29 Feat/#1 main page 1
  package.json
  src/pages/main/Board.jsx
  src/pages/main/BoardList.jsx
  src/pages/main/BoardPlusButton.jsx
  src/pages/main/EditButton.jsx
  src/pages/main/Main.jsx
  src/pages/main/PageButton.jsx
  src/pages/main/main.css
Labels: 구현

#30 Feat/#23 Implement server request for detail page data
  src/pages/detail/Main.jsx
  src/pages/detail/Practice.jsx
  src/pages/detail/Question.jsx
  src/pages/detail/TIL.jsx
Labels: 구현

#34 타이머 기능 및 모달 CSS 수정
  src/pages/Practice.jsx
  src/pages/detail/ContentsLeft.css
  src/pages/main/main.css
  src/pages/practice/Main.jsx
  src/pages/practice/Submit.jsx
  src/pages/practice/Timer.jsx
  src/routers/AppRouter.jsx
Labels: 버그수정, 구현

#36 Nginx에서 SSE 연결 유지 문제
  nginx.conf
Labels: 버그수정

#38 실습 상세 페이지 데이터 연동 및 상태 관리 기능 구현
  src/components/Logo.jsx
  src/pages/practice/Answer.jsx
  src/pages/practice/Assignment.jsx
  src/pages/practice/Main.jsx
  src/pages/practice/Submit.jsx
  src/pages/practice/Timer.jsx
Labels: 구현

#40 JWT 및 SSE 통합을 통한 실시간 질문 큐 구현
  src/pages/main/Question.jsx
Labels: 구현

#42 Feat/#23 detail
  src/pages/detail/Practice.jsx
  src/pages/detail/detail.css
  src/routers/AppRouter.jsx
Labels: 구현, 디자인

#45 실습 상세 페이지 오류 수정
  src/pages/practice/Answer.jsx
  src/pages/practice/Assignment.jsx
  src/pages/practice/Main.jsx
  src/pages/practice/Submit.jsx
Labels: 버그수정, 구현

#46 질문 & 답글 관련 CRUD API 프론트 연동
  src/pages/detail/Question.jsx
Labels: 구현

#48 메인 페이지 및 실습 상세 페이지 비인가 접근 방지
  src/pages/main/Main.jsx
  src/pages/practice/Main.jsx
Labels: 구현

#50 브라우저 탭 제목 및 파비콘 수정
  index.html
Labels: 구현

#52 404 Not Found 페이지 스타일 개선
  src/pages/NotFound.jsx
Labels: 구현, 디자인

#54 Feat/#23 detail api
  src/pages/detail/TIL.jsx
  src/pages/detail/detail.css
Labels: 구현, 디자인
